/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSelect: typeof import('./components/AppSelect.vue')['default']
    Comment: typeof import('./components/Comment.vue')['default']
    CommentInput: typeof import('./components/CommentInput.vue')['default']
    DevConfig: typeof import('./components/settings/DevConfig.vue')['default']
    Drauu: typeof import('./components/Drauu.vue')['default']
    FriendsCommentInput: typeof import('./components/themes/FriendsCommentInput.vue')['default']
    FriendsMemo: typeof import('./components/themes/FriendsMemo.vue')['default']
    FriendsMemoInput: typeof import('./components/themes/FriendsMemoInput.vue')['default']
    Import: typeof import('./components/settings/Import.vue')['default']
    LeftNav: typeof import('./components/LeftNav.vue')['default']
    MarkdownInput: typeof import('./components/Markdown-input.vue')['default']
    MeAll: typeof import('./components/MeAll.vue')['default']
    Memo: typeof import('./components/Memo.vue')['default']
    MemoInput: typeof import('./components/MemoInput.vue')['default']
    Mine: typeof import('./components/Mine.vue')['default']
    RightNav: typeof import('./components/RightNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Statistics: typeof import('./components/Statistics.vue')['default']
    SysConfig: typeof import('./components/settings/SysConfig.vue')['default']
    TagManage: typeof import('./components/settings/TagManage.vue')['default']
    Top10Tag: typeof import('./components/Top10Tag.vue')['default']
    UserConfig: typeof import('./components/settings/UserConfig.vue')['default']
  }
}
